/*
 * Commitlint 配置
 * @generated by @robot-admin/git-standards
 *
 * 直接修改此文件即可自定义提交校验规则
 */
module.exports = {
  extends: ['@commitlint/config-conventional'],
  rules: {
    'type-enum': [
      2,
      'always',
      [
        'wip', 'feat', 'fix', 'docs', 'style', 'refactor',
        'perf', 'test', 'chore', 'revert', 'build', 'deps',
      ],
    ],
    'scope-empty': [2, 'never'],  // 强制要求 scope
    'subject-case': [0],
  },
}
